pluginManagement {
    repositories {
        gradlePluginPortal() // Access plugins from the Gradle Plugin Portal
        google()             // Required for Android Gradle plugin
        mavenCentral()       // Required for other plugins and libraries
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") } // JitPack repository
    }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "DW"

include ':app'
include ':audioplayer'
include ':router'
include ':core:network'
include ':core:preferences'
include ':core:shared-preference-impl'
include ':features:feature-card'
include ':features:games:common:game-results'
include ':features:games:common:game-rules'
include ':features:games:crossword'
