package com.pramod.dailyword.framework.prefmanagers

import android.content.Context
import android.content.Context.MODE_PRIVATE
import android.content.SharedPreferences
import androidx.preference.PreferenceManager

open class BasePreferenceManager(prefName: String?, base: Context) {

    /**
     * if preference name is provided then create new or get existing preference file
     * else get default preference file generated by app
     */
    val sPrefManager: SharedPreferences by lazy {
        prefName?.let {
            base.getSharedPreferences(prefName, MODE_PRIVATE)
        } ?: PreferenceManager.getDefaultSharedPreferences(base)
    }

    val editor: SharedPreferences.Editor = sPrefManager.edit()


}