name: Run test

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Create key.properties files from Secrets
        run: |
          touch key.properties
          echo "GOOGLE_LICENSE_KEY=${{ secrets.GOOGLE_LICENSE_KEY }}" >> key.properties
          echo "MERCHANT_ID=${{ secrets.MERCHANT_ID }}" >> key.properties
          echo "GOOGLE_IN_APP_RSA_KEY=${{ secrets.GOOGLE_IN_APP_RSA_KEY }}" >> key.properties

      - name: Create endpoint.properties files from Secrets
        run: |          
          touch endpoint.properties
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> endpoint.properties
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> endpoint.properties
          echo "WORLD_TIME_BASE_URL=${{ secrets.WORLD_TIME_BASE_URL }}" >> endpoint.properties
          echo "GET_WORD_OF_THE_DAY=${{ secrets.GET_WORD_OF_THE_DAY }}" >> endpoint.properties
          echo "GET_WORDS=${{ secrets.GET_WORDS }}" >> endpoint.properties
          echo "GET_WORDS_PAGING=${{ secrets.GET_WORDS_PAGING }}" >> endpoint.properties
          echo "GET_RANDOM_WORD=${{ secrets.GET_RANDOM_WORD }}" >> endpoint.properties
          echo "PRIVACY_POLICY=${{ secrets.PRIVACY_POLICY }}" >> endpoint.properties
          echo "TERM_AND_CONDITION=${{ secrets.TERM_AND_CONDITION }}" >> endpoint.properties
          echo "GET_PUBLIC_IP=${{ secrets.GET_PUBLIC_IP }}" >> endpoint.properties
          echo "GET_IP_DETAILS=${{ secrets.GET_IP_DETAILS }}" >> endpoint.properties
          echo "HOME_BACKGROUND_URL=${{ secrets.HOME_BACKGROUND_URL }}" >> endpoint.properties

      - name: Create google-services.json from Secrets
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Run unit tests
        run: ./gradlew testDebug
